name: master pipeline

on:
  push:
    branches:
      - master
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm i

      - name: Test
        run: npm test

      - name: Build
        run: CI=false npm run build